### ISSUE TITLE
Research Animation libraries

### ISSUE THREAD

**Issue by alessiojorge** [interfacers/reactor#3]

**Comment by ttraenkler** [comment]
In addition to looking into the Web Animations API, it might be good to know about these popular libraries:
- Greensock is the de facto standard for animations and often referred to by professionals, even when talking about the Web Animations API: https://greensock.com/ - its open source but has a commercial version as well
- Anime.js is a relatively new but neveretheless very popular open source animation library that might be good to know about: https://animejs.com/

**Comment by ttraenkler** [comment]
Another option is to just use plain css in combination with styled-components or plain stylesheet Javascript apis to manipulate the transforms. I think we should probably gather some experience with the vanilla javascript dom and cssom APIs  to learn more about how animations work under the hood and what needs we have to use a higher level library which might help pick a library where it's useful and not use one where it's not needed.

**Comment by ttraenkler** [comment]
I think we can close this task for now and create a new one once we have more hands on experience.

**Comment by ttraenkler** [comment]
https://www.mediaevent.de/javascript/css-animation.html
